### ISSUE TITLE
Latest breaks .NET Framework compatibility

### ISSUE THREAD

**Issue by cormacrelf** [Narochno/Narochno.Credstash#8]
I love the speed at which you fixed the HMAC upstream. Unfortunately, this now targets netcoreapp1.1, which means it can no longer be used with the .NET Framework. I can't tell from the commit log exactly what has required this change; as far as I can tell, af87a3e5e243 just switches for the sake of it.

Could you switch back to netstandard, please? The only difference between netcoreapp and netstandard of the same version number is that netcoreapp builds can include a runtime and build executables. Given this is a library, I think netstandard should be just fine.

**Comment by adamhathcock** [comment]
Oh crap!  I just noticed that.

For some reason my eyes glazed over the fact that that said `netcoreapp` and not `netstandard`  I will fix.

**Comment by cormacrelf** [comment]
Mate, my original version of this issue managed to screw it up until a ninja edit 4 seconds later.

Thanks.

**Comment by adamhathcock** [comment]
Should be up as 1.1.1
